# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  entity_id:
    type: string
    description: Identifier of the IdP entity (must be a URI)
  metadata_url:
    type: string
    description: URL to the IdP's metadata
  fingerprint:
    type: string
    description: SHA256 Fingerprint to validate the metadata URL's public certificate. If empty, no validation is performed
